defaults: &defaults
  docker:
    - image: circleci/node:carbon
  working_directory: ~/babel-plugin-transform-modules-commonjs

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/babel-plugin-transform-modules-commonjs
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-
      - run: 
          name: Install Dependencies
          command: npm install
      - run: 
          name: Compile Code
          command: npm run build
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/babel-plugin-transform-modules-commonjs
      - run: npm run ci

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/babel-plugin-transform-modules-commonjs
      - run: 
          name: Set git user
          command: |
            git config --global user.email "vincecoppola@gmail.com"
            git config --global user.name "Vince Coppola"
      - run: 
          name: Bump version
          command: npm run release
      - run: 
          name: Push tags
          command: |
            mkdir ~/.ssh
            cat << EOF > ~/.ssh/config
            Host *
                StrictHostKeyChecking    no
            EOF
            git push --tags
      - run: 
          name: Publish
          command: npm publish
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
